### ISSUE TITLE
Service stops with UTF-8 decode error

### ISSUE THREAD

**Issue by nicolasjon** [iu5jae/pYSFReflector#25]
The Reflector runs much more reliably than the previous one I was using(!) Great work.
Every week or so I get an error like the following or a general parsing related error and the service stops. Any thoughts?
Thanks

Feb 02 13:08:44 zbm2 systemd[1]: Starting YSFReflector...
Feb 02 13:08:46 zbm2 systemd[1]: Started YSFReflector.
Feb 03 09:33:18 zbm2 python3[899]: Starting pYSFReflector-20210606
Feb 03 09:33:19 zbm2 python3[899]: Traceback (most recent call last):
Feb 03 09:33:19 zbm2 python3[899]:   File "/usr/local/bin/YSFReflector", line 922, in <module>
Feb 03 09:33:19 zbm2 python3[899]:     RunServer(config)
Feb 03 09:33:19 zbm2 python3[899]:   File "/usr/local/bin/YSFReflector", line 666, in RunServer
Feb 03 09:33:19 zbm2 python3[899]:     tx_ok = canTrasmit(data[14:24].decode().strip(), CheckRE)
Feb 03 09:33:19 zbm2 python3[899]: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa2 in position 4: invalid start byte

**Comment by iu5jae** [comment]
it seems a problem given by an invalid character, I check, thanks for the report !!

**Comment by iu5jae** [comment]
Can you try the latest version to check if the problem is solved?

**Comment by nicolasjon** [comment]
Thanks! I have updated the GB7SV reflector. I will keep you posted. Thanks again for your great work.
